### ISSUE TITLE
Chat convert failing with v2

### ISSUE THREAD

**Issue by c-hri-s** [Zibbp/ganymede#340] opened 2024-01-03 14:04 UTC
I've upgraded to v2 and none of the live streams since then have completed processing.

The video seems to process okay, but the chat fails:

![image](https://github.com/Zibbp/ganymede/assets/13216128/831dcdea-ff3f-4348-80f4-589da2d7e044)

```
TwitchDownloaderCLI 1.53.6 Copyright (c) lay295 and contributors

[STATUS] - Updating Video Info [1/3]Unhandled exception. System.AggregateException: One or more errors occurred. (Input string was not in a correct format.)
 ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus , TypeCode )
   at System.Number.ParseInt32(ReadOnlySpan`1 , NumberStyles , NumberFormatInfo )
   at System.Int32.Parse(String )
   at TwitchDownloaderCore.ChatUpdater.UpdateVideoInfo(Int32 totalSteps, Int32 currentStep, IProgress`1 progress, CancellationToken cancellationToken)
   at TwitchDownloaderCore.ChatUpdater.UpdateAsync(IProgress`1 progress, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at TwitchDownloaderCLI.Modes.UpdateChat.Update(ChatUpdateArgs inputOptions)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at TwitchDownloaderCLI.Program.Main(String[] args)
```

**Comment by Zibbp** [comment] 2024-01-03 23:12
Can you provide the channel name so I can take a look? Does the channel have any previous videos?

**Comment by c-hri-s** [comment] 2024-01-04 11:14
It's done the same thing on every live it's recorded since I installed 2.0.
Some of them have one or two previous videos, some have none.

https://www.twitch.tv/owensouthdj
https://www.twitch.tv/djcquence
https://www.twitch.tv/caitlinpotter

Are there any other useful logs which I could pull for you?

```
TwitchDownloaderCLI 1.53.6 Copyright (c) lay295 and contributors

[STATUS] - Updating Video Info [1/3]Unhandled exception. System.AggregateException: One or more errors occurred. (Input string was not in a correct format.)
 ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus , TypeCode )
   at System.Number.ParseInt32(ReadOnlySpan`1 , NumberStyles , NumberFormatInfo )
   at System.Int32.Parse(String )
   at TwitchDownloaderCore.ChatUpdater.UpdateVideoInfo(Int32 totalSteps, Int32 currentStep, IProgress`1 progress, CancellationToken cancellationToken)
   at TwitchDownloaderCore.ChatUpdater.UpdateAsync(IProgress`1 progress, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at TwitchDownloaderCLI.Modes.UpdateChat.Update(ChatUpdateArgs inputOptions)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at TwitchDownloaderCLI.Program.Main(String[] args)

```

**Comment by Zibbp** [comment] 2024-01-04 23:57
The issue is likely that TwitchDownloader now requires a video ID when running the "chatupdate" command. As these channels do not have previous videos it can't find a video to use. Do you see the following error messages in the API container logs when the chat is attempted to be converted?
```
5:38PM WRN Unable to convert chat due to no previous video IDs
5:38PM DBG Converting Twitch Live Chat to Vod Chat
5:38PM ERR error running TwitchDownloaderCLI for chat update error="signal: aborted (core dumped)"
```
I can likely use any video ID in lieu of the channel not have any videos available. Doing some testing now.

**Comment by Zibbp** [comment] 2024-01-05 02:57
I've pushed a possible fix to the `main` branch available using the `:main` image tag for the API container. If you're able to, can you update your API container to use the `:main` image tag when nothing is being archived to try it out? Note that the `/workflows` page will be broken on `:main`. Maybe spin up a new instance to quickly try it out?

**Comment by c-hri-s** [comment] 2024-01-05 10:21
I couldn't find the older api logs (where are they stored?!), I just had thousands of *-chat *-video *-video-convert etc. logs in the /logs folder. Scrolling through the live log for the api container was painful as it had been spitting out something about the failed chat convert every few seconds for the past week or so and there were SO many entries.

I've installed :main, will let you know later how it goes as there's a stream scheduled today which it should capture.

> Can you provide the channel name so I can take a look? Does the channel have any previous videos?

Sorry, I misunderstood that question when I answered it previously - I thought you meant did I have any previous videos stored in ganymede for these channels, not did any prior videos exist on Twitch.

**Comment by c-hri-s** [comment] 2024-01-05 16:49
The changes in `:main` seem to have done the trick!

```
TwitchDownloaderCLI 1.53.6 Copyright (c) lay295 and contributors

[STATUS] - Updating Video Info [1/3]
[STATUS] - Updating Embeds [2/3]
[LOG] - Input 3rd party emote count: 0. Output count: 2

[LOG] - Input bit emote count: 0. Output count: 2

[LOG] - Input badge count: 0. Output count: 12

[LOG] - Input 1st party emote count: 0. Output count: 457

[STATUS] - Writing Output File [3/3]
```

**Comment by Zibbp** [comment] 2024-01-05 22:48
Awesome, I'll publish a release this weekend with this fix.

**Comment by Zibbp** [comment] 2024-01-07 19:40
Released in https://github.com/Zibbp/ganymede/releases/tag/v2.0.2

**Closed by Zibbp** 2024-01-07 19:40 UTC
Labels: bug
